
title: Gabriele Pintus
email: gabrielegpintus@gmail.com
description: >-
  Welcome to my blog!
domain: gabrielepintus.github.io
baseurl: ""
url: "https://gabrielepintus.github.io"
github_username:  GabrielePintus

# Build settings
theme: minima
plugins:
  - jekyll-feed

highlighter: rouge
kramdown:
  math_engine: katex
  syntax_highlighter: rouge



include:
  - _includes/head_custom.html
